"""Single source of truth for the mandatory report disclaimers."""

from __future__ import annotations

DISCLAIMER = (
    "**Disclaimer:** This report is generated by **MIIP** (Michael Investment Intelligence "
    "Platform) for research and decision-support only. It contains relative research "
    "signals, not financial advice, recommendations, or predictions. Nothing here is "
    "personalised to your circumstances. Scores come from manually entered readings and "
    "configured models — they may be wrong or stale. Do your own research and consult a "
    "licensed professional before making any investment decision."
)

MANUAL_DATA_NOTICE = (
    "**Manual / static data:** All figures are from hand-entered configuration and "
    "`data/market_snapshot.yaml`. They are **not** live market data, broker balances, "
    "or verified prices. Do not treat outputs as real-time market conclusions."
)

# Backward-compatible alias used in tests
PLACEHOLDER_NOTICE = MANUAL_DATA_NOTICE
